FROM python:3.11-slim

WORKDIR /app

COPY front/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY front/ .

EXPOSE 8501

CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0"]